service:
  name: Worker Cluster
  version: "1.0.0"
  debug: false

rabbitmq:
  host: localhost
  port: 5672
  user: guest
  password: guest

redis:
  host: localhost
  port: 6383
  db: 0

api:
  host: "0.0.0.0"
  port: 8006

worker:
  max_concurrency: 10
  prefetch_count: 1
